name: Mise à jour calendrier Châtillon DM4

on:
  schedule:
    - cron: "15 6 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-chatillon-calendar:

    runs-on: ubuntu-latest

    steps:

      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Installer les dépendances
        run: |
          pip install -r requirements-chatillon.txt

      - name: Générer le calendrier
        run: |
          python generate_chatillon_calendar.py

      - name: Enregistrer les modifications
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add calendrier-chatillon.ics

          git diff --cached --quiet || git commit -m "Mise à jour calendrier Châtillon DM4"

          git push
